/**
 * Main type exports - barrel file for all type definitions
 * This file serves as the central export point for all types used throughout the application
 */

// Common utility types
export type {
	BaseComponentProps,
	FormComponentProps,
	ModalProps,
	LoadingState,
	PaginationParams,
	PaginationResponse,
	SelectOption,
	ExtendedSelectOption,
	FilterParams,
	SortParams,
	Address,
	Hash,
	Timestamp,
	ID,
	ContractStandard,
	TransactionStatus,
	HttpMethod,
	AsyncResult,
	VoidCallback,
	ValueCallback,
	AsyncCallback,
	AsyncValueCallback,
} from './common';

// API-related types
export type {
	ApiError,
	ApiResponse,
	ApiRequestOptions,
	UseApiReturn,
	User,
	AuthState,
	Chain,
	TimelockContract,
	TimelockContractItem,
	TimelockParameters,
	ImportTimelockRequest,
	CreateTimelockRequestBody,
	TimelockApiResponse,
	Transaction,
	TransactionListResponse,
	TransactionStats,
	TransactionListFilters,
	PendingTransactionFilters,
	Partner,
	ABIItem,
	ABIListResponse,
	Asset,
	AssetsData,
	UseAssetsApiReturn,
	EmailNotification,
	EmailNotificationListResponse,
	EmailLog,
	CreateEmailNotificationRequest,
	UpdateEmailNotificationRequest,
	VerifyEmailRequest,
	ResendCodeRequest,
	EmergencyReplyRequest,
	EmailNotificationFilters,
	SponsorsData,
	SponsorsApiResponse,
	RawTx,
	PendingTx,
} from './api';

// Blockchain and Web3 types
export type {
	TransactionResult,
	OpenZeppelinTimelockParams,
	DeployContractParams,
	SendTransactionParams,
	Web3State,
	UseWeb3Return,
	ChainConfig,
	ChainIdMapping,
	TimelockABI,
	ContractValidationResult,
	NetworkInfo,
	GasEstimation,
	TransactionReceipt,
	WalletConnectionOptions,
	ContractCallParams,
	ContractReadResult,
	ContractWriteResult,
	TimelockAdminPermissions,
	TimelockOperation,
	MultiSigWallet,
	TokenInfo,
	TokenBalance,
} from './blockchain';

// Component prop types
export type {
	ButtonVariant,
	ButtonSize,
	ButtonProps,
	InputProps,
	CardProps,
	RadioButtonOptionProps,
	ChainOption,
	StandardOption,
	StandardOptionConfig,
	ParameterDisplayRowProps,
	ContractStandardSelectionProps,
	CreationDetails,
	ConfirmCreationDialogProps,
	CreateTimelockFormProps,
	CreateTimelockFormState,
	DeploymentResult,
	CompoundTimelockParams,
	SidebarContextProps,
} from './components';

// Form-related types
export type {
	FormError,
	FormState,
	FormFieldConfig,
	UseFormReturn,
	LoginFormData,
	CreateTimelockFormData,
	ImportTimelockFormData,
	CreateTransactionFormData,
	EmailNotificationFormData,
	ABIFormData,
	ABIRow,
	ABIContent,
	AddABIFormProps,
	ViewABIFormProps,
	EncodingTransactionFormProps,
	TargetABISectionProps,
	MailboxSelectionProps,
	EncodingPreviewProps,
	ProfileFormData,
	SettingsFormData,
	SearchFormData,
	FilterFormData,
	ValidationSchemas,
	FormProps,
	FormFieldProps as FormFieldComponentProps,
	FormSectionProps,
	FormActionsProps,
	DynamicFormField,
	DynamicFormConfig,
	FormWizardStep,
	FormWizardConfig,
	FormWizardProps,
} from './forms';

// Re-export commonly used React types for convenience
export type { ReactNode, ComponentProps, FC, PropsWithChildren } from 'react';
