/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    WealthProofRegistry: {
      address: "0xa513e6e4b8f2a923d98304ec87f64353c4d5c853",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "allInstances",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "createProofInstance",
          inputs: [
            {
              name: "walletPool",
              type: "address[32]",
              internalType: "address[32]",
            },
          ],
          outputs: [
            {
              name: "instance",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getAllInstances",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getInstanceVerifications",
          inputs: [
            {
              name: "instance",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "records",
              type: "tuple[]",
              internalType: "struct WealthProofRegistry.VerificationRecord[]",
              components: [
                {
                  name: "instance",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "verifier",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "threshold",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "result",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "timestamp",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getUserInstances",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getVerificationCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "userInstances",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "verifications",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "instance",
              type: "address",
              internalType: "address",
            },
            {
              name: "verifier",
              type: "address",
              internalType: "address",
            },
            {
              name: "threshold",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "result",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "verifier",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract Groth16Verifier",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "verifyAndRecord",
          inputs: [
            {
              name: "instance",
              type: "address",
              internalType: "address",
            },
            {
              name: "proof",
              type: "bytes",
              internalType: "bytes",
            },
            {
              name: "threshold",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "result",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "InstanceCreated",
          inputs: [
            {
              name: "creator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "instance",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "walletPool",
              type: "address[32]",
              indexed: false,
              internalType: "address[32]",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ProofVerified",
          inputs: [
            {
              name: "instance",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "verifier",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "threshold",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "result",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 10,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
