// Contract addresses - read from environment variables (auto-generated by hardhat/scripts/export-abis.ts)
export const contracts = {
  mockCTF: (import.meta.env.VITE_MOCK_CTF_ADDRESS || '0x0000000000000000000000000000000000000000') as `0x${string}`,
  mockUSDC: (import.meta.env.VITE_MOCK_USDC_ADDRESS || '0x0000000000000000000000000000000000000000') as `0x${string}`,
  rewardToken: (import.meta.env.VITE_REWARD_TOKEN_ADDRESS || '0x0000000000000000000000000000000000000000') as `0x${string}`,
  stakingBribe: (import.meta.env.VITE_STAKING_BRIBE_ADDRESS || '0x0000000000000000000000000000000000000000') as `0x${string}`,
  bribeManager: (import.meta.env.VITE_BRIBE_MANAGER_ADDRESS || '0x0000000000000000000000000000000000000000') as `0x${string}`,
  ponyProtocol: (import.meta.env.VITE_PONY_PROTOCOL_ADDRESS || '0x0000000000000000000000000000000000000000') as `0x${string}`,
} as const;

// Localhost Hardhat Network
export const CHAIN_ID = 31337;
export const CHAIN_NAME = 'Hardhat Local';
export const RPC_URL = 'http://127.0.0.1:8545';
export const BLOCK_EXPLORER = '';

// Faucet URLs
export const FAUCETS = {
  matic: '', // No external faucet needed for localhost
  usdc: '/faucet', // Internal USDC faucet page
} as const;
